using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using XoneExecutionAck.Database.Entities;

namespace XoneExecutionAck.Database.CompiledModels
{
    // This class provides a pre-compiled model for Entity Framework Core
    // to use in AOT (Ahead-of-Time) compilation scenarios
    public static class AppDbContextModel
    {
        // This is a placeholder for the actual compiled model
        // In a real AOT scenario, this would be generated by the EF Core tools
        public static IModel GetModel()
        {
            var modelBuilder = new ModelBuilder();

            // Configure the ExecutionRecord entity
            modelBuilder.Entity<ExecutionRecord>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.HasIndex(e => e.ExecutionId)
                    .IsUnique();

                entity.Property(e => e.RawData)
                    .HasColumnType("jsonb");
            });

            // Build and return the model
            return modelBuilder.FinalizeModel();
        }
    }
}
